In [4]:
import numpy as np

In [5]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [18]:
import numpy as np
arr = np.linspace(2,11,5)
print(arr)

[ 2.    4.25  6.5   8.75 11.  ]


In [14]:
import numpy as np

arr = np.linspace(2, 11, 5)
print(arr)


[ 2.    4.25  6.5   8.75 11.  ]


In [19]:
np.random.rand(10))

array([0.10512239, 0.88172783, 0.47585557, 0.59952446, 0.69022183,
       0.19750757, 0.86665682, 0.8746091 , 0.00353761, 0.7295019 ])

In [23]:
np.random.randn(5)

array([-0.01321247, -2.16167577,  0.5771713 , -0.9411073 , -0.15091823])

In [25]:
np.random.randint(10,20,5)


array([15, 17, 14, 12, 12], dtype=int32)

In [28]:
arr = np.arange(1,15)

In [30]:
arr = np.arange(1,15)

arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [31]:
arr.shape

(14,)

In [32]:
arr.size

14

In [33]:
arr.dtype

dtype('int64')

In [34]:
arr.min()

np.int64(1)

In [35]:
arr.max()

np.int64(14)

In [36]:
arr.sum()

np.int64(105)

In [37]:
arr.mean()

np.float64(7.5)

In [38]:
arr.argmax()

np.int64(13)

In [39]:
arr.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [40]:
arr[9]

np.int64(10)

In [41]:
arr[1:5]

array([2, 3, 4, 5])

In [4]:
import numpy as np
brr = np.arange(11,31)
brr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [11]:
bool=brr%2==0
bool
arr=brr[bool]
arr

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [13]:
arr

array([12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [12]:
crr=arr+brr
crr

array([24, 28, 32, 36, 40, 44, 48, 52, 56, 60])

In [17]:
drrr=crr+10
drrr

array([34, 38, 42, 46, 50, 54, 58, 62, 66, 70])

In [19]:
err=drrr@crr
err

np.int64(23160)